View/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'View'
urlpatterns = [
    path('',views.homes,name='home2'),
    path('deal-index/',views.home,name='home'),
url(r'^index',views.home,name='index'),
path('login/',views.login2,name='login'),
path('logout/',views.log_uerout,name='logout'),
    path('welcome/<str:token>', views.verifyAccount),
    path('signup/',views.create_account,name='signup2'),
    path('login/',views.verification_login,name='login_uri'),
    url(r'^profile/',views.user_profile,name='myprofile'),
    path('save_deal',views.save_deal,name='create_deal'),
    path('clear_deal/<str:token>',views.deal_clearance,name='clear_deal'),
    path('clearance/',views.save_clearance,name="verify_deal"),
    path('listing/<int:pk>',views.deal_deail,name="deal-details"),
    url(r'^signup',views.sign_up,name='sign-up'),
    path('save_form/',views.registar,name='registar'),
        path('mydeals/',views.user_deals,name='mydeal'),
    url(r'^request-deal/',views.deal_process,name="request_deal"),
        url(r'^dashboard/',views.dashboard,name="dashboard"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

appl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('View.urls')),
    path('deals_manager/',include('Backend.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

View/templates/generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title%}{% endblock title%}</title>
<link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
<link rel="stylesheet" type="text/css" href="{%static 'css/style.css'%}" >
<link rel="stylesheet" type="text/css" href="{%static 'css/generic.css'%}" >

</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0
&appId=1797597976998779&autoLogAppEvents=1"></script>
<header>
<a id="brand-name">Deals <span id="b">Connect</span></a>
<nav class="nav">
{%if user.is_authenticated %}
<a id="links">{{user.first_name}} {{user.last_name}}</a>
<a id="links" style="float:left;"><image src="{{profile.image.url}}" class="img-circle img-responsive"></a>
<a id="links" href="{% url 'View:myprofile' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
{% else %}
<a id="links" class="reg"><i class="fas fa-user-plus"></i>Signup</a>

<a id="links" class="login"><i class="fas fa-lock"></i>Login</a>
{% endif %}

</nav>
</header>
<div class="main">
{%block contents%}
{% endblock contents%}
</div>
<div class="container col-sm-8" id="signup" >
<form method="POST" action="{% url 'View:signup2' %}">
{% csrf_token %}

	<div class="form-group ">
		
		    
        <input name="first_name" class="form-control" id="id_first_name"
		placeholder="First Name" type="text" required>
    </div>
	<div class="form-group ">
		
        <input name="last_name" class="form-control" id="id_last_name"
		placeholder="Last Name" type="text" required>
    </div>
	 <!-- form-group// -->
    <div class="form-group ">
    	
		 <p id="error"></p>
        <input name="email" class="form-control" placeholder="Email address"  
		type="email" id="id_email" required>
    </div> <!-- form-group// -->
    <div class="form-group ">
    	
		
    	<input name="phone" class="form-control" placeholder="Phone number"
		 type="text" id="phone" required>
    </div> <!-- form-group// -->
 <div class="form-group ">
    	
		<select class="form-control" name="gender" id="gender" required>
			<option selected=""> Select Gender</option>
			<option value="female">Female</option>
			<option value="male">Male</option>
			<option value="other">Other</option>
		</select>
	</div>
	<div class="form-group ">
		
        <input name="username" class="form-control" id="id_username"
		placeholder="Username" type="text" required>
    </div>
    <div class="form-group ">
    	
        <input class="form-control" name="password" id="pass1" placeholder="Create password"
		 type="password" required>
    </div> <!-- form-group// -->
    <div class="form-group ">
    
        <input class="form-control" id="pass2" placeholder="Repeat password" 
		type="password" required>
    </div> <!-- form-group// -->                                      
        <button type="submit" id='submit' class="btn btn-primary btn-block btn-lg"> Create Account  </button>
    </div> <!-- form-group// -->      
                                                                    
</form>
</div>
</div>
</div>
</div>
</div>
<div class="container-fluid " id="form">

<form class="form" action="{% url 'View:login' %}" method="POST">
{% csrf_token %}
<div class="fb-login-button" data-width="" data-size="large" data-button-type="continue_with" 
data-auto-logout-link="false" data-use-continue-as="false"></div>
<p></p>
<div class="form-group">
<label><i class="fa fa-user" style="color:white;"></i></label>

<input type="text" class="form-control" placeholder="username" name="username">
</div>
<div class="form-group">
<label><i class="fa fa-lock" style="color:white;"></i></label>

<input type="password" class="form-control" placeholder="password" name="pass">
</div>
<button  type="submit" class="btn btn-block btn-success">Login</button>


</div>
</div>

</form>

<footer>
<div class="container">
<ul style="float:left">
<li id="ft-menu"><h4>Site Map</h4>
<li id="ft-menu"><a>Contact</a></li>
<li id="ft-menu"><a>About</a></li>
<li id="ft-menu"><a>Home</a></li>
<li id="ft-menu"><a>Faq</a></li>


</ul>
<ul style="float:left">
<li id="ft-menu"><h4></h4>
<li id="ft-menu"><a>Terms and Condition</a></li>
<li id="ft-menu"><a>Create a deal</a></li>
</ul>
<form style="float:left">
<ul>
<li id="ft-menu"><h4>Subscribe to mail List..</h4></li>
</ul>
<div class="form-group">
<input type="email" class="form-control" placeholder="@example.com">
</div>
<button type="submit" class="btn btn-secondery" > Submit</button>
</form>
</div>
</div>
</footer>
<script>
$(document).ready(function(){
$('.reg').click(function(){
	$('#signup').modal({
				modalClass: "login",

	});
});

$('.login').click(function(){
	$('.form').modal({
		modalClass: "login",
	});
});
})
</script>
<!-- Remember to include jQuery :) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<!-- jQuery Modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
</body>
</html>

View/templates/user-head.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<!------ Include the above in your HEAD tag ---------->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="sumit kumar">
  

 <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
			  crossorigin="anonymous"></script>
  <title>admin-template</title>
 

      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
      

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="{% static 'css/panel.css'%}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/deal.css'%}" rel="stylesheet" type="text/css">

  <!--TABLE SCRIPT-->
     <script src="{% static 'js/tabular/modules/accessor.js'%}"></script>
          <script src="{% static 'js/tabular/modules/calculation_colums.js'%}"></script>
            <script src="{% static 'js/tabular/modules/download.js'%}"></script>
                        <script src="{% static 'css/tabular/modules/filter.js'%}"></script>
                              <script src="{% static 'css/tabular/modules/format.js'%}"></script>
        <script src="{% static 'js/tabular/modules/html_table_export.js'%}"></script>
                <script src="{% static 'js/tabular/modules/print.js'%}"></script>
                                <script src="{% static 'js/tabular/modules/select_row copy.js'%}"></script>
                        <script src="{% static 'js/tabular/modules/select_row.js'%}"></script>
                                                <script src="{% static 'js/tabular/modules/sort.js'%}"></script>

   <script src="{% static 'js/tabular/jquery_wrapper.js'%}"></script>
      <script src="{% static 'js/tabular/tabulator_core.js'%}"></script>
         <script src="{% static 'js/tabular/tabulator.js'%}"></script>
             <link  href="{% static 'css/tableexport.css' %}" rel="stylesheet" media="screen"  type="text/css">

         <script type="text/javascript" src="http://oss.sheetjs.com/js-xlsx/xlsx.full.min.js"></script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.5/jspdf.plugin.autotable.js"></script>
   <!--END SCRIPT-->

 <script src="https://use.fontawesome.com/07b0ce5d10.js"></script>
 
 </head>

<body>
  <!--=============================
                                             NAVIGATION
                                   =============================-->
  <!--top nav start=======-->
  <nav class="navbar navbar-inverse top-bar navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button> <span class="menu-icon" id="menu-icon"><i class="fa fa-times" aria-hidden="true" id="chang-menu-icon"></i></span>
        <a class="navbar-brand" href="#"><img src="https://lh3.googleusercontent.com/-N4NB2F966TU/WM7V1KYusRI/AAAAAAAADtA/fPvGVNzOkCo7ZMqLI6pPITE9ZF7NONmawCJoC/w185-h40-p-rw/logo.png" width="90%"> </a>
      </div>
      <div class="collapse navbar-collapse navbar-right" id="myNavbar">
        <form class="navbar-form navbar-left">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i> </button>
            </div>
          </div>
        </form>
        <ul class="nav navbar-nav">
          <li class=""><a href="#"><i class="fa fa-refresh"></i> Start Tour</a> </li>
          <li class=""><a href="#"><i class="fa fa-volume-up"></i></a> </li>
          <li class=""><a href="#"><i class="fa fa-envelope"></i> <span class="badge">5</span></a> </li>
          <li class=""><a href="#"><i class="fa fa-bell"></i> <span class="badge">9</span></a> </li>
          <li class="">
            <a href="#" class="user-profile"> <span class=""><img class="img-responsive" src="https://lh3.googleusercontent.com/-HxSAl6WJSI0/WM-dbkQ1ONI/AAAAAAAADuY/RsjaXC3tg4oBozCUYyLr12ZjZ1_Cl91mACJoC/w424-h319-p-rw/sumit.png"></span> </a>
          </li>
          <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sumit          
           <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <a href="#"><i class="fa fa-user"></i> Profile</a> </li>
              <li> <a href="#"><i class="fa fa-cog"></i> Setting</a> </li>
              <li> <a href="#"><i class="fa fa-power-off"></i> Logout</a> </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!--    top nav end===========-->
  <div class="wrapper" id="wrapper">
    <div class="left-container" id="left-container">
      <!-- begin SIDE NAV USER PANEL -->
      <div class="left-sidebar" id="show-nav">
        <ul id="side" class="side-nav">
          <li class="panel">
            <a id="panel1" href="{% url 'View:dashboard'%}" data-toggle="collapse" data-target="#Dashboard"> <i class="fa fa-dashboard"></i> Dashboard
              <i class="fa fa-chevron-left pull-right" id="arow1"></i> </a>
          
          </li>
          <li class="panel">
            <a id="panel2" href="{% url 'View:myprofile'%}" data-toggle="collapse" data-target="#charts"> <i class="fa fa-book"></i>Create Deal
              <i class="fa fa-chevron-left pull-right" id="arow2"></i> </a>
            
          </li>
          <li class="panel">
            <a id="panel4" href="{% url 'View:request_deal'%}" data-toggle="collapse" data-target="#clipboard"> <i class="fa fa-clipboard"></i> Request a Deal
              <i class="fa fa fa-chevron-left pull-right" id="arow4"></i> </a>
        
          </li>
          <li class="panel">
            <a id="panel5" href="javascript:;" data-toggle="collapse" data-target="#edit"> <i class="fa fa-edit"></i>
            Settings
              <i class="fa fa fa-chevron-left pull-right" id="arow5"></i>
            </a>
         
          </li>
           <li class="panel">
            <a id="panel4" href="{% url 'View:mydeal'%}" data-toggle="collapse" data-target="#clipboard"> <i class="fa fa-clipboard"></i> My Deal Request
              <i class="fa fa fa-chevron-left pull-right" id="arow4"></i> </a>
        
          </li>
          <li class="panel">
            <a id="panel6" href="javascript:;" data-toggle="collapse" data-target="#inbox"> <i class="fa fa-inbox"></i> Message
              <span class="label label-primary">new msz</span> <i class="fa fa fa-chevron-left pull-right" id="arow6"></i> </a>
          
          </li>
           <li class="panel">
            <a id="panel6"  data-toggle="collapse" href="/logout"> <i class="fa fa-lock"></i>logout</a>
          
          </li>
          
        </ul>
      </div>
      <!-- END SIDE NAV USER PANEL -->
    </div>
    <div class="right-container" id="right-container">
     {%block content%}
  {% endblock%}   
  </div>
  
  <script src="js/jquery-3.1.1.js"></script>
  <script src="js/bootstrap.js"></script>
   
  <script type="text/javascript">
    $(document).ready(function() {
      $("#panel1").click(function() {
        $("#arow1").toggleClass("fa-chevron-left");
        $("#arow1").toggleClass("fa-chevron-down");
      });
        
      $("#panel2").click(function() {
        $("#arow2").toggleClass("fa-chevron-left");
        $("#arow2").toggleClass("fa-chevron-down");
      });
        
      $("#panel3").click(function() {
        $("#arow3").toggleClass("fa-chevron-left");
        $("#arow3").toggleClass("fa-chevron-down");
      });
        
      $("#panel4").click(function() {
        $("#arow4").toggleClass("fa-chevron-left");
          $("#arow4").toggleClass("fa-chevron-down");
      });
        
      $("#panel5").click(function() {
        $("#arow5").toggleClass("fa-chevron-left");
        $("#arow5").toggleClass("fa-chevron-down");
      });
        
      $("#panel6").click(function() {
        $("#arow6").toggleClass("fa-chevron-left");
        $("#arow6").toggleClass("fa-chevron-down");
      });
        
      $("#panel7").click(function() {
        $("#arow7").toggleClass("fa-chevron-left");
        $("#arow7").toggleClass("fa-chevron-down");
      });
        
      $("#panel8").click(function() {
        $("#arow8").toggleClass("fa-chevron-left");
        $("#arow8").toggleClass("fa-chevron-down");
      });
        
      $("#panel9").click(function() {
        $("#arow9").toggleClass("fa-chevron-left");
        $("#arow9").toggleClass("fa-chevron-down");
      });
        
      $("#panel10").click(function() {
        $("#arow10").toggleClass("fa-chevron-left");
        $("#arow10").toggleClass("fa-chevron-down");
      });
        
      $("#panel11").click(function() {
        $("#arow11").toggleClass("fa-chevron-left");
        $("#arow11").toggleClass("fa-chevron-down");
      });
        
      $("#menu-icon").click(function() {
        $("#chang-menu-icon").toggleClass("fa-bars");
        $("#chang-menu-icon").toggleClass("fa-times");
        $("#show-nav").toggleClass("hide-sidebar");
        $("#show-nav").toggleClass("left-sidebar");
          
        $("#left-container").toggleClass("less-width");
        $("#right-container").toggleClass("full-width");
      });
        
     
        
    });
  </script>
    
    
    
    
    
    
    
    
    
    
    
    
    
</body>

</html>