Backend/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name='Backend'
urlpatterns = [
    path('web-manager/',views.index,name="web-master"),
    path('manage-user/', views.manage_user,name="user-manager"),
    path('user-detail/<int:pk>', views.user_detail,name="details"),
    path('deal_request/<str:token>',views.save_deal,name="save-deal"),
        path('my_request/',views.save_deals,name="my-request"),
path('user_admin/',views.user_manage,name='user-admin'),
     path('deal_detail/<int:pk>',views.deal_details,name="deal-detail"),
    path('dealstatus/',views.deal_status,name="dealstatus"),
 path('request_record/',views.deal_record,name="request-record"),
  path('request_moderation/<str:code>',views.deal_moderation,name="deal_moderation"),
    path('request_moderation/',views.approve_request,name="reqstatus"),
        path('user_record/',views.users_record,name="user-record"),
            path('user_detail<int:pk>/',views.user_detail,name="user-detail"),
                path('settings/',views.settings,name="settings"),



]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

View/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'View'
urlpatterns = [
    path('',views.homes,name='home2'),
    path('deal-index/',views.home,name='home'),
url(r'^index',views.home,name='index'),
path('login/',views.login2,name='login'),
path('logout/',views.log_uerout,name='logout'),
    path('welcome/<str:token>', views.verifyAccount),
    path('signup/',views.create_account,name='signup2'),
    path('login/',views.verification_login,name='login_uri'),
    url(r'^profile/',views.user_profile,name='myprofile'),
    path('save_deal',views.save_deal,name='create_deal'),
    path('clear_deal/<str:token>',views.deal_clearance,name='clear_deal'),
    path('clearance/',views.save_clearance,name="verify_deal"),
    path('listing/<int:pk>',views.deal_deail,name="deal-details"),
    url(r'^signup',views.sign_up,name='sign-up'),
    path('save_form/',views.registar,name='registar'),
        path('mydeals/',views.user_deals,name='mydeal'),
    url(r'^request-deal/',views.deal_process,name="request_deal"),
        url(r'^dashboard/',views.dashboard,name="dashboard"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

appl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('View.urls')),
    path('deals_manager/',include('Backend.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

View/models.py
import sys
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from PIL import Image
from django.conf import settings
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.
class Profile(models.Model):
    state = models.CharField(null=True,blank=True, max_length=50)
    city = models.CharField(null=True,blank=True, max_length=50)
    mobile_no = models.CharField(null=False,blank=False, max_length=50,)
    address= models.CharField( max_length=50,null=True,blank=True)
    image = models.ImageField(upload_to='user/%d/%m/%y', null=True, 
                            blank=True,default=settings.AVARTA)
    gender = models.CharField(null=True,blank=True, max_length=50)
    education= ArrayField(models.CharField(null=True,blank=True, max_length=50),
                      null=True,blank=True)
    work=models.CharField(null=True,blank=True, max_length=50)
    about = models.TextField(null=True,blank=True)
    is_verified = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    def save(self, *args, **kwargs):
        if not self.id:
            self.image = self.compressImage(self.image)
        super(Profile, self).save(*args, **kwargs)
    def compressImage(self,image):
        imageTemproary = Image.open(image)
        outputIoStream = BytesIO()
        imageTemproaryResized = imageTemproary.resize( (1020,573) ) 
        imageTemproary.save(outputIoStream , format='JPEG', quality=80)
        outputIoStream.seek(0)
        image = InMemoryUploadedFile(outputIoStream,'ImageField', "%s.*" % image.name.split('.')[0], 'image/jpeg', sys.getsizeof(outputIoStream), None)
        return image
    def __str__(self):
        return self.state
    class Meta:
        permissions=(("is_staff","A staff"),)
                    
    def get_absolute_url(self):
        return reverse("profile_detail", args=str([self.id]))
class Cleanser(models.Model):
    names = models.CharField(blank=True,null=True, max_length=50)
    image = models.ImageField( upload_to='cleanser/%d/%m/%y')
    address= models.CharField( max_length=50,blank=True,null=True)
    state= models.CharField(max_length=50,blank=True,null=True)
    city = models.CharField( max_length=50,blank=True,null=True)
    mobile_no = models.CharField(max_length=50,blank=True,null=True)
    token = models.CharField(blank=True,null=True,max_length=50)
    def get_absolute_url(self):
        return reverse("cleanser-detail",args=str([self.id]) )
class Category(models.Model):
       name = models.CharField( max_length=50)
       op = models.ForeignKey(User, on_delete=models.CASCADE)
       date = models.DateTimeField( auto_now=True, auto_now_add=False)
class Deals(models.Model):
    title = models.CharField( max_length=50)
    token = models.CharField(blank=True,null=True, max_length=50)
    about = models.TextField(max_length=120)
    op = models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)
    status = models.BooleanField(default=False)
    framework = ArrayField(models.CharField(max_length=50))
    is_valid = models.BooleanField(default=False)
    moderator = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    date = models.DateTimeField( auto_now=True, auto_now_add=False)
    views = models.IntegerField(blank=True, null=True,default=0)
    is_verified = models.BooleanField(blank=True,null=True)

    def __str__(self):
        return self.op
        class META:
            ordering = ['date','title']
    def get_absolute_url(self):
        return reverse("deal_detail", args=str([self.slug]))
class Mydeals(models.Model):
    deal_code= models.CharField( max_length=50,blank=True,null=True)
    deal_id = models.ForeignKey(Deals, on_delete=models.CASCADE,blank=True,null=True)
    title = models.CharField(blank=True,null=True,max_length=50)
    owner= models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)
    status = models.CharField(max_length=50,default="pending")
    is_fufilled = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now=True, auto_now_add=False)
    date_fufiled = models.DateTimeField(auto_now=True, auto_now_add=False)
    def __str__(self):
        return self.user
class Request(models.Model):
    title = models.CharField(max_length=50)
    op = models.ForeignKey(User,blank=True,null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True, auto_now_add=False)
    text = models.CharField( max_length=50)
    def __str__(self):
        return self.user
class Message(models.Model):
    to = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    files = models.FileField(blank=True,null=True,upload_to="message/%d/%m/%y", max_length=50)
class Reply(models.Model):
    text = models.TextField()
    to = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    files = models.FileField(blank=True,null=True, upload_to="reply/%d/%m/%y", max_length=100)
class Payment(models.Model):
    payee = models.ForeignKey(User, on_delete=models.CASCADE)
    deal_code = models.CharField( max_length=50)
    bank = models.CharField( max_length=50)
    amount = models.CharField( max_length=50)
    teller= models.ImageField( upload_to="teller/%d/%m/%y", max_length=50)

View/templates/view/deal-clearance.html
{%extends 'generic.html'%}
{% block title%}
{{deal.about}}
{% endblock title%}
{% block contents%}


<div class='container'>
    <div class='row' style='padding-top:25px; padding-bottom:25px;'>
        <div class='col-md-12'>
            <div id='mainContentWrapper'>
                <div class="col-md-8 col-md-offset-2">
                    <h2 style="text-align: center;">
                      <!--  Verify deal {{user.first_name}} {{user.last_name}} <img ="{{profile.image.url}}"
                        class="img-circle img-responsive">-->
                    </h2>
                    <hr/>
                   <!-- <a href="#" class="btn btn-info" style="width: 100%;">Add More Products & Services</a>-->
                    <hr/>
                    <div class="shopping_cart">
                        <form class="form-horizontal" role="form" action="{% url 'View:verify_deal' %}" method="post"
                         id="payment-form" enctype="multipart/form-data" >
                         <input type="hidden" name="token" value="{{deal.token}}">
                            <div class="panel-group" id="accordion">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h4 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Review
                                                Deal</a>
                                        </h4>
                                    </div>
                                    <div id="collapseOne" class="panel-collapse collapse in">
                                        <div class="panel-body">
                                            <div class="items">
                                                <div class="col-md-9 col-sm-4">
                                                    <table class="table table-striped">
                                                        <tr>
                                                            <td colspan="2">
                                                                <b>
                                                                    {{deal.title}}</b></td>
                                                        </tr>
                                                        <tr>
                                                            <td>
                                                            <h4>Framework</h4>
                                                                <ul>
                                                                
                                                                {% for i in framework%}
                                                                    <li>{{i}}</li>
                                                                {% endfor %}
                                                                </ul>
                                                            </td>
                                                           
                                                        </tr>
                                                    </table>
                                                </div>
                                               
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <div style="text-align: center; width:100%;"><a style="width:100%;"
                                                                                        data-toggle="collapse"
                                                                                        data-parent="#accordion"
                                                                                        href="#collapseTwo"
                                                                                        class=" btn btn-success"
                                                                                        onclick="$(this).fadeOut(); $('#payInfo').fadeIn();">Input
                                            your Information to verify Deal»</a></div>
                                    </h4>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Deal 
                                        Cleanser Details</a>
                                    </h4>
                                </div>
                                <div id="collapseTwo" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <b>Help us keep your account safe and secur
                                            information.</b>
                                        <br/><br/>
                                        <table class="table table-striped" style="font-weight: bold;">
                                            <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_first_name">Full name:</label></td>
                                                <td>
                                                    <input class="form-control" id="id_first_name" name="names"
                                                           required="required" type="text" required/>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_address_line_1">Address:</label></td>
                                                <td>
                                                    <input class="form-control" id="id_address_line_1"
                                                           name="address" required="required" type="text" required/>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_address_line_2">Unit / Suite #:</label></td>
                                                <td>
                                                    <input class="form-control" id="id_address_line_2"
                                                           name="address_line_2" type="text" required />
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_city">City:</label></td>
                                                <td>
                                                    <input class="form-control" id="id_city" name="city"
                                                           required="required" type="text" required/>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_state">State:</label></td>
                                                <td>
                                                    <select class="form-control" id="id_state" name="state" required>
                                                        <option value="Abia">Abia</option>
                                        <option value="Adamawa">Adamawa</option>
                                        <option value="Akwa Ibom">Akwa Ibom</option>
                                        <option value="Anambra">Anambra</option>
                                        <option value="Bauchi"> Bauchi</option>
                                        <option value="Bayelsa">Bayelsa</option>
                                        <option value="Benue">Benue</option>
                                        <option value="Borno">Borno</option>
                                        <option value="Cross River">Cross River</option>Cross River
                                        <option value="Delta">Delta</option>
                                        <option value="Ebonyi">Ebonyi</option>
                                        <option value="Enugu">Enugu</option>
                                        <option value="Edo">Edo</option>
                                        <option value="Ekiti">Ekiti</option>
                                        <option value="Gombe">Gombe</option>
                                        <option value="Imo">Imo</option>
                                        <option value="Jigawa">Jigawa</option>
                                        <option value="Kaduna">Kaduna</option>
                                        <option value="Kano">Kano</option>
                                        <option value="Katsina">Katsina</option>
                                        <option value="Kebbi">Kebbi</option>
                                        <option value="Kogi">Kogi</option>
                                        <option value="Kwara">Kwara</option>
                                        <option value="Lagos">Lagos</option>
                                        <option value="Nasarawa">Nasarawa</option>
                                        <option value="Niger">Niger</option>
                                        <option value="Ogun">Ogun</option>
                                        <option value="Ondo">Ondo</option>
                                        <option value="Osun">Osun</option>
                                        <option value="Oyo">Oyo</option>
                                        <option value="Plateau">Plateau</option>
                                        <option value="Rivers">Rivers</option>
                                        <option value="Sokoto">Sokoto<option>
                                                <option value="Taraba">Taraba</option>
                                                <option value="Yobe">Yobe</option>
                                                <option value="Zamfara">Zamfara</option>
                                                <option value="FCT Abuja">FCT Abuja</option>
                                                    </select>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_phone">Phone:</label></td>
                                                <td>
                                                    <input class="form-control" id="id_phone" name="phone" type="text" required/>
                                                </td>
                                            </tr>
                                             <tr>
                                                <td style="width: 175px;">
                                                    <label for="id_phone">Picture:</label></td>
                                                <td>
                                                    <input class="form-control" id="id_phone" name="image" type="file" required/>
                                                </td>
                                            </tr>
{% csrf_token %}
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success btn-lg" style="width:100%;">
                                            Verify 
                                        </button
                </form>
            </div>
        </div>
    </div>



{% endblock contents%}

View/templates/view/deal-detail.html
{% extends 'generic.html' %}
{% block contents %}
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
         
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{deal.title}}</h3>
            </div>
            <div class="panel-body">
            <p>{{deal.about}}</p>
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                
              
                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                    {% for d in deal.framework %}
                      <tr>
                        <td><i class="far fa-hand-point-right"></i></td>
                        <td>{{d}}</td>
                      </tr>
                      {% endfor %}
                      
                   
                         <tr>
                     
                    </tbody>
                  </table>
                  
                  <a href="{% url 'Backend:save-deal' deal.token %}" class="btn btn-primary">Request Deal</a>
                </div>
              </div>
            </div>
                 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                            <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
                            <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
                        </span>
                    </div>
            
          </div>
        </div>
      </div>
    </div>
{% endblock%}

View/templates/view/deal_request.html
{% extends 'user-head.html'%}

{% block content%}
<style>
.red{
    color:red;
    }
.form-area
{
    background-color: #FAFAFA;
	padding: 10px 40px 60px;
	margin: 10px 0px 60px;
	border: 1px solid GREY;
	}
</style>

<div class="container">
<div class="col-md-5">
    <div class="form-area">  
        <form role="form" action="{%url 'Backend:my-request'%}" method="POST">
        {% csrf_token%}
        <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Request Deal</h3>
    				<div class="form-group">
						<input type="text" class="form-control" id="name" name="title" placeholder="title" required>
					</div>
					
                    <div class="form-group">
                    <textarea class="form-control" type="textarea" name="about" id="message" placeholder="Message" maxlength="140" rows="7"></textarea>
                        <span class="help-block"><p id="characterLeft" class="help-block ">You have reached the limit</p></span>                    
                    </div>
            
        <button type="submit" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form</button>
        </form>
    </div>
</div>
</div>
</div>
<script>
$(document).ready(function(){ 
    $('#characterLeft').text('140 characters left');
    $('#message').keydown(function () {
        var max = 140;
        var len = $(this).val().length;
        if (len >= max) {
            $('#characterLeft').text('You have reached the limit');
            $('#characterLeft').addClass('red');
        } 
        else {
            var ch = max - len;
            $('#characterLeft').text(ch + ' characters left');
            $('#btnSubmit').removeClass('disabled');
            $('#characterLeft').removeClass('red');            
        }
    });    
});

</script>
{% endblock %}

View/templates/view/deals.html
{%extends 'generic.html'%}

{% block contents%}
<div class="container-fluid">

    <div class="row">
               
{%for deal in deals%}
                <div class="col-sm-6">  

                    <!-- Begin Listing: 1220-32 N HOWARD ST-->
					
                    <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                        <div class="media">
                            <a class="pull-left" href="#" target="_parent">
                            <!--<img alt="image" class="img-responsive" src="http://images.prd.mris.com/image/V2/1/vGoNjc2jHGb87GlnnDQlf6LxeOUgIOn0bL6Wvn1nEnig2Ntq6W7xN5cOQBZZeNxl9O42DOkHUw0LNnj1ZB2KHA.jpg">-->
                            </a>

                            <div class="clearfix visible-sm"></div>

                            <div class="media-body fnt-smaller">
                                <a href="#" target="_parent"></a>

                                <h4 class="media-heading">
                                  <a href="{%url 'View:deal-details' deal.pk %}" target="_parent">{{deal.title}}<small class="pull-right"></small></a></h4>


                                <ul class="list-inline mrg-0 btm-mrg-10 clr-535353">
								{% for f in deal.framework %}
                                    <li>{{f}}</li>

                                    <li style="list-style: none">|</li>
									{%endfor%}
                                    
                                </ul>

                                <p class="hidden-xs">. ...</p><span class="fnt-smaller fnt-lighter fnt-arial">{{deal.about}}</span>
                            </div>
                        </div>
                    </div>
					
					<!-- End Listing-->

                    

                   
                </div>
                
				{% endfor %}
                </div>
{% endblock contents%}

View/templates/view/error.html
{%extends 'generic.html'%}
{%block contents%}
<div class="container">
<h3 style="text-align:center; color:red;;">{{message}}</h3>
</div>
{%endblock contents%}

View/templates/view/index.html
{%extends 'generic.html'%}
{% block title %}
Deals Connect 
{% endblock %}
{%block contents%}


<div class="banner">
<h2 style="text-align:center; color:white;font-size:2em;"> Welcome to Deals Connect Test Site</h2>
</div>
<div id="search">
<span>
<form >
<div class="search">
<input type="text" placeholder="search a deal" required>
<select id="select">
<option>Select Category</option>
</select>
<button type="submit"><i class="fas fa-search"></i>search..</button>
</div>
</div>
 </form>  
</span>
 <div class="container-fluid" style="background-color:#e8e8e8">
        <div class="container container-pad" id="property-listings">
            
            <div class="row">
              <div class="col-md-12">
                <h1 style="text-align:center; font-size:1.5em;">Feautured Deals</h1>
              </div>
            </div>
            
            <div class="row">
               
{%for deal in deals%}
                <div class="col-sm-6">  

                    <!-- Begin Listing: 1220-32 N HOWARD ST-->
					
                    <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing">
                        <div class="media">
                            <a class="pull-left" href="#" target="_parent">
                            <!--<img alt="image" class="img-responsive" src="http://images.prd.mris.com/image/V2/1/vGoNjc2jHGb87GlnnDQlf6LxeOUgIOn0bL6Wvn1nEnig2Ntq6W7xN5cOQBZZeNxl9O42DOkHUw0LNnj1ZB2KHA.jpg">-->
                            </a>

                            <div class="clearfix visible-sm"></div>

                            <div class="media-body fnt-smaller">
                                <a href="#" target="_parent"></a>

                                <h4 class="media-heading">
                                  <a href="{%url 'View:deal-details' deal.pk %}" target="_parent">{{deal.title}}<small class="pull-right"></small></a></h4>


                                <ul class="list-inline mrg-0 btm-mrg-10 clr-535353">
								{% for f in deal.framework %}
                                    <li>{{f}}</li>

                                    <li style="list-style: none">|</li>
									{%endfor%}
                                    
                                </ul>

                                <p class="hidden-xs">. ...</p><span class="fnt-smaller fnt-lighter fnt-arial">{{deal.about}}</span>
                            </div>
                        </div>
                    </div>
					
					<!-- End Listing-->

                    

                   
                </div>
                
				{% endfor %}
				<!-- End Col -->
            </div><!-- End row -->
        </div><!-- End container -->
    </div>
    {% block javascript %}
  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });
  </script>
  <div class="loading" style="display: none;">
    Loading...
  </div>
<div class="container" style="text-align:center"  >
  {% if deals.has_next %}
    <a style="text-align:center" class="infinite-more-link" href="?page={{ deals.next_page_number }}">
    <button class="btn btn-success btn-inline">next &raquo;</button></a>
  {% endif %}
   {% if deals.has_previous %}
            <a style="text-align:center"  href="?page=1">&laquo; first</a>
            <a  style="text-align:center" href="?page={{ deals.previous_page_number }}"><button class="btn btn-primary  btn-inline">
           &laquo; previous</button></a>
        {% endif %}
  </div>
{% endblock %}
 {%endblock contents%}

View/templates/view/success.html
{%extends 'generic.html'%}
{%block contents%}
<div class="container">
<h2 style="text-align:center; color:green">{{message}}</h2>
</div>
{%endblock contents%}