Backend/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name='Backend'
urlpatterns = [
    path('web-manager/',views.index,name="web-master"),
    path('manage-user/', views.manage_user,name="user-manager"),
    path('user-detail/<int:pk>', views.user_detail,name="details"),
    path('deal_request/<str:token>',views.save_deal,name="save-deal"),
        path('my_request/',views.save_deals,name="my-request"),
path('user_admin/',views.user_manage,name='user-admin'),
     path('deal_detail/<int:pk>',views.deal_details,name="deal-detail"),
    path('dealstatus/',views.deal_status,name="dealstatus"),
 path('request_record/',views.deal_record,name="request-record"),
  path('request_moderation/<str:code>',views.deal_moderation,name="deal_moderation"),
    path('request_moderation/',views.approve_request,name="reqstatus"),
        path('user_record/',views.users_record,name="user-record"),
            path('user_detail<int:pk>/',views.user_detail,name="user-detail"),
                path('settings/',views.settings,name="settings"),



]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

View/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'View'
urlpatterns = [
    path('',views.homes,name='home2'),
    path('deal-index/',views.home,name='home'),
url(r'^index',views.home,name='index'),
path('login/',views.login2,name='login'),
path('logout/',views.log_uerout,name='logout'),
    path('welcome/<str:token>', views.verifyAccount),
    path('signup/',views.create_account,name='signup2'),
    path('login/',views.verification_login,name='login_uri'),
    url(r'^profile/',views.user_profile,name='myprofile'),
    path('save_deal',views.save_deal,name='create_deal'),
    path('clear_deal/<str:token>',views.deal_clearance,name='clear_deal'),
    path('clearance/',views.save_clearance,name="verify_deal"),
    path('listing/<int:pk>',views.deal_deail,name="deal-details"),
    url(r'^signup',views.sign_up,name='sign-up'),
    path('save_form/',views.registar,name='registar'),
        path('mydeals/',views.user_deals,name='mydeal'),
    url(r'^request-deal/',views.deal_process,name="request_deal"),
        url(r'^dashboard/',views.dashboard,name="dashboard"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

appl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('View.urls')),
    path('deals_manager/',include('Backend.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Backend/models.py
from django.db import models

# Create your models here.
class EmailToken(models.Model):
    token= models.CharField(max_length=50)
    uid = models.BigIntegerField()

Backend/views.py
from django.shortcuts import render,reverse,redirect,HttpResponse,get_object_or_404
from View.models import Deals,Profile,Mydeals,Request
from django.contrib.auth.models import User
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import JsonResponse
from django.contrib import auth
import random
from Backend.sms import SMS
from Backend.mymail import MAIL
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
# Create your views here.
def index(request):
    deal = Deals.objects.all()
    return render(request,'backend/index.html',{'deal':deal})
def manage_user(request):
    profile=Profile.objects.all()
    users = User.objects.all()
    return render(request,'backend/manage-user.html',{'users':users,'profile':profile})
#Manage Use Details
def user_detail(request,pk):
    user = get_object_or_404(User,pk=pk)
    profile = get_object_or_404(Profile,user_id=user.pk)
    return render(request,'backend/user-detail.html',{'user':user,'profile':profile})
#User administration
@csrf_exempt
@require_http_methods(['POST'])
def user_manage(request):
    payload= request.POST.get('payload',None)
    token= request.POST.get('token',None)
    user = get_object_or_404(User,pk=token)


    
    if payload == "staff":
        content_type = ContentType.objects.get_for_model(Profile)
        permission = Permission.objects.get(codename='is_staff',content_type=content_type,)
        user.user_permissions.add(permission)

        user.save()      

        data ={'msg':'Approved'}      
        return JsonResponse(data)
    elif payload == "suspend":
        user.is_active = False
        user.save()
        data={'msg':'suspended'}
        return JsonResponse(data)
    elif payload == "enable":
        user.is_active = True
        user.save()
        data={'msg':'enabled'}
        return JsonResponse(data)
    else:
        user.delete()
        data={'msg':'deleted'}
        return JsonResponse(data)
    return redirect('Backend:index')
#Deal Request
def save_deal(request,token):
    track_code =   random.randint(100,1000)
    deal = get_object_or_404(Deals,token=token)
    if request.user.is_authenticated:
        uid = request.session['userId']
        user = get_object_or_404(User,pk=uid)
        mydeal = Mydeals.objects.create(deal_code=track_code)
        mydeal.save()
        mydeal.title=deal.title
        mydeal.deal_id=deal
        mydeal.owner = user
        mydeal.save()
        return redirect('View:mydeal')
    else:
        request.session['deal']=token
        return redirect('View:sign-up')
    return HttpResponse('Error')

#Deal Validation
def deal_details(request,pk):
    deal =get_object_or_404(Deals,pk=pk)
    uid=deal.op_id
    profile = get_object_or_404(Profile,pk=uid)
    
    user = get_object_or_404(User,pk=profile.user_id)
    return render(request,'backend/manage-deal.html',{'deal':deal,'profile':profile,'user':user})
#Deal Status
@csrf_exempt
@require_http_methods(['POST'])
def deal_status(request):
    payload= request.POST.get('payload',None)
    token= request.POST.get('token',None)
    uid = request.session['userId']
    user = get_object_or_404(User,pk=uid)


    deal= get_object_or_404(Deals,token=token) 
    deal.moderator=user
    deal.save()
    if payload == "approve":
        deal.valid=True
        deal.is_valid=True

        deal.save()      
        userename=user.first_name
        email=user.email
        data ={'msg':'Approved'}
        deal.status =True
        deal.save()
             
        return JsonResponse(data)
    elif payload == "decline":
        deal.valid =False
        deal.save()
        data={'msg':'Declined'}
        deal.status = False
        deal.save()
         
        return JsonResponse(data)

    elif payload == "suspend":
        deal.status = False
        deal.save()
        data={'msg':'Suspended'}
         
        return JsonResponse(data)
    else:
        deal.delete()
        data ={'msg':'deleted'}
        return JsonResponse(data)
    return redirect('Backend:index')

@csrf_protect
@require_http_methods(['POST'])
def save_deals(request):
    title= request.POST.get('title',None)
    about = request.POST.get('about',None)
    uid = request.session['userId']
    user = get_object_or_404(User,pk=uid)
    req = Request.objects.create(title=title,text=about,op=user)
    req.save()
    return redirect('View:dashboard')

#DEAL REQUEST RECORD
def deal_record(request):
    mydeal= Mydeals.objects.all()
    return render(request,'backend/deal_record.html',{'mydeal':mydeal})
#DEAL REQUEST MODERATION
def deal_moderation(request,code):
    mydeal= get_object_or_404(Mydeals, deal_code=code)
    #Get the Deal object
    deal_id = mydeal.deal_id_id
    deal = get_object_or_404(Deals,pk=deal_id)
    # Deal owner object
    deal_owner = deal.op_id
    profile_owner = get_object_or_404(Profile,pk=deal_owner)
    owner = get_object_or_404(User,pk=profile_owner.user_id)
    #Deal Request owner objeck
    request_user =get_object_or_404(User,pk=mydeal.owner_id)
    #Request Owner Profile
    profile_request =get_object_or_404(Profile,user_id=request_user.id)
    return render(request,'backend/request-details.html',{'mydeal':mydeal,'deal':deal,'owner':owner,'profile':profile_request,
                                                        'req':request_user,'profile_owner':profile_owner})
@csrf_exempt
@require_http_methods(['POST'])
def approve_request(request):
    payload= request.POST.get('payload',None)
    token= request.POST.get('token',None)


    deal= get_object_or_404(Mydeals,deal_code=token) 
    deal.save()
    if payload == "approve":
        deal.is_fufilled=True
        deal.save()
        deal.save()  
        deal.status='successful'    
        data ={'msg':'Approved'}
        deal.save()    
          
        return JsonResponse(data)
    elif payload == "decline":
        deal.is_fufilled =False
        deal.save()
        deal.status='declined'
        deal.save()
        data={'msg':'Declined'}
        deal.save()
         
        return JsonResponse(data)
    return redirect('Backend:request-record')

def users_record(request):
    users= User.objects.all()
    return render(request,'backend/manage-user.html',{'user':users})

#Settings
def settings(request):
    return render(request,'backend/settings.html')

Backend/templates/backend/deal_record.html
{% extends 'base.html'%}
{%block content%}

 <div class="container-fluid">
 <table id="example" class="display nowrap">
    <thead>
        <tr>
            <th width="200">Deal Code</th>
        <th width="200">Title</th>

            <th tabulator-align="center">Deal Progress</th>
            <th>Request Date</th>
                 <th width="200">status</th>

        </tr>
    </thead>
    <tbody>
    {% for d in mydeal%}
        <tr>
       
            <td scope="row"><a href="{% url 'Backend:deal_moderation' d.deal_code %}">{{d.deal_code}}</a></td>
                        <td scope="row">{{d.title}}</td>

            {% if d.is_fufilled == False %}
            <td scope="row">  <div class="progress">
                           <div data-placement="top" style="width: 40%;" 
                              aria-valuemax="100" aria-valuemin="0" aria-valuenow="70" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">70% </span>
                              <span class="progress-type">Under Processing</span>
                           </div>
                        </div></td>
            {% else %}
        <td scope="row">
         <div class="progress">
                           <div data-placement="top" style="width:100%;" 
                              aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">100% </span>
                              <span class="progress-type">Processed</span>
                           </div>
                        </div> 
        </td>
        {% endif %}
<td>{{d.date}}</td>
<td>{{d.status}}</td>

        </tr>
        {%endfor%}
    </tbody>
</table>

 </div>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );

</script>
 <script type="text/javascript" src=" https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src ="https://code.jquery.com/jquery-3.3.1.js"></script>


<script type="text/javascript" src  = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.flash.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.print.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/css/buttons.dataTables.min.css"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
{% endblock %}

Backend/templates/backend/index.html
{% extends 'base.html'%}
{% block content%}
<style>

</style>
 <div class="container-fluid">
 <table id="example" class="display nowrap">
    <thead>
        <tr>
            <th width="200">Title</th>
            <th tabulator-align="center">Status</th>
            <th>Validity Status</th>
            <th>Date</th>
            <th width="150">Cleansing Status</th>
            <th>View</th>
        </tr>
    </thead>
    <tbody>
    {% for d in deal%}
        <tr>
       
            <td scope="row"><a href="{% url 'Backend:deal-detail' d.pk %}">{{d.title}}</a></td>
            {% if d.status == False %}
            <td style="color:red;">inactive</td>
            {%else%}
            <td style="color:green;">active</td>

            {% endif %}
            {% if d.is_valid == False %}
            <td style="color:red;">invalid</td>
            {% else %}
            <td style="color:green;">valid</td>
            {%endif%}
            <td>{{d.date}}</td>
           {% if d.is_verified == False %}
            <td style="color:red;">unverified</td>
            {% else %}
            <td style="color:green;">verified</td>
            {%endif%}
            <td>{{d.views}}</td>
        </tr>
        {%endfor%}
    </tbody>
</table>
 </div>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );

</script>
 <script type="text/javascript" src=" https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src ="https://code.jquery.com/jquery-3.3.1.js"></script>


<script type="text/javascript" src  = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.flash.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.print.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/css/buttons.dataTables.min.css"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
{%endblock%}

Backend/templates/backend/manage-deal.html
{% extends 'base.html' %}
{% block content %}

<!------ Include the above in your HEAD tag ---------->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
<div class="row">
    <div class="col-sm-3">
        <a href="mail-compose.html" class="btn btn-danger  btn-compose-email">Delete User</a>
        <ul class="nav nav-pills nav-stacked nav-email shadow mb-20">
            <li class="active">
                <a href="#mail-inbox.html">
                    <i class="fa fa-inbox"></i> User Request <span class="label pull-right">7</span>
                </a>
            </li>
            <li>
                <a href="#mail-compose.html"><i class="fa fa-envelope-o"></i> Send Message</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-certificate"></i> Important</a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-file-text-o"></i> View Cleanser Detail <span class="label label-info pull-right inbox-notification">
                </a>
            </li>
            <li><a href="#"> <i class="fa fa-trash-o"></i>Delete</a></li>
        </ul><!-- /.nav -->

       
    </div>
    <div class="col-sm-9">
        
        <!-- resumt -->
        <div class="panel panel-default">
               <div class="panel-heading resume-heading">
                  <div class="row">
                     <div class="col-lg-12">
                        <div class="col-xs-12 col-sm-4">
                           <figure>
                              <img class="img-circle img-responsive" alt="" src="{{profile.image.url}}">
                           </figure>
                           <div class="row">
                              <div class="col-xs-12 social-btns">
                                 <div class="  ">
                                    <button class="btn btn-success  btn-block" id="approve">
                                    Approve deal </button>
                                 </div>
                                 <div class="  ">
                                    <button class="btn btn-danger  btn-block " id="decline">
                                    Decline Deal</button>
                                 </div>
                                 <div class="  ">
                                    <button class="btn btn-primary btn-block " id="suspend">
                                    Suspend Deal </button>
                                 </div>
                                 <div class=" ">
                                    <button class="btn btn-default btn-block " id="delete">
                                    Dealete Deal</button>
                                 </div>
                              </div>
                              
                              
                           </div>
                        </div>
                        <div class="col-xs-12 col-sm-8">
                           <ul class="list-group">
                              <li class="list-group-item"><b>First Name:</b> {{user.first_name}}</li>
                              <li class="list-group-item"><b>Last Name:</b>{{user.last_name}}</li>
                              <li class="list-group-item"><i class="fa fa-phone"></i>
                              <b></b> {{profile.mobile_no}} </li>
                              <li class="list-group-item"><i class="fa fa-envelope"></i> {{user.email}} </li>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="bs-callout bs-callout-danger">
                  <h4>About Deal</h4>
                  <p>
                    {{deal.about}}
                  </p>

                        <p></p>
                     </a>
                  </ul>
               </div>
               <div class="bs-callout bs-callout-danger">
                  <h4>Deal Frameworkworks</h4>
                  <ul class="list-group">
                  {% for d in deal.framework %}
                     <li class="list-group-item"> {{d}}</li>
                     {% endfor %}
                  </ul>
                  </ul>
               </div>
               <div class="bs-callout bs-callout-danger">
                  <h4>Deal Progress</h4>
                  <ul class="list-group">
                     <a class="list-group-item inactive-link" href="#">
                     {% if deal.is_verified == True %}
                        <div class="progress">
                           <div data-placement="top" style="width:70%;" 
                              aria-valuemax="100" aria-valuemin="0" aria-valuenow="70" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">80%</span>
                              <span class="progress-type">Cleaned</span>
                           </div>
                        </div>
                        {% elif deal.is_verified == False %}
                        <div class="progress">
                           <div data-placement="top" style="width: 10%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" role="progressbar" class="progress-bar progress-bar-danger">
                              <span class="sr-only">10%</span>
                              <span class="progress-type">No Cleaser</span>
                           </div>
                           </div>
                        {% elif deal.status == True %}
                         <div class="progress">
                           <div data-placement="top" style="width: 80%;" 
                              aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">100% </span>
                              <span class="progress-type">Approved</span>
                           </div>
                        </div>
                       
                      {% elif deal.valid == True%}
                       <div class="progress">
                           <div data-placement="top" style="width:100%;" 
                              aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" role="progressbar" class="progress-bar progress-bar-success">
                              <span class="sr-only">100%</span>
                              <span class="progress-type">Moderated</span>
                           </div>
                        </div>
                      {% else %}
                        <div class="progress">
                           <div data-placement="top" style="width: 10%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" role="progressbar" class="progress-bar progress-bar-danger">
                              <span class="sr-only">100%</span>
                              <span class="progress-type">Inactive</span>
                           </div>
                           </div>
                        {% endif %}
                        </div>
                        <div class="progress-meter">
                           <div style="width: 25%;" class="meter meter-left"><span class="meter-text"> Clensing</span></div>
                           <div style="width: 25%;" class="meter meter-left"><span class="meter-text">Cleaned</span></div>
                           <div style="width: 30%;" class="meter meter-right"><span class="meter-text">Validation</span></div>
                           <div style="width: 20%;" class="meter meter-right"><span class="meter-text">Moderation</span></div>
                        </div>
                     </a>
                  </ul>
               </div>
               <div class="bs-callout bs-callout-danger">
                  <h4></h4>
                  <table class="table table-striped table-responsive ">
                     <thead>
                        <tr>
                           <th>Views</th>
                          <!-- <th>ratings</th>-->
                        <!-- <th>reviews</th>-->

                        </tr>
                     </thead>
                     <tbody>
                        <tr>
                           <td>{{deal.views}}</td>
                          <!-- <td>2014</td>-->
                        </tr>
                       <!-- <tr>
                           <td>BSc. in Computer Science and Engineering</td>
                          
                        </tr>-->
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
        <!-- resume -->

    </div>
</div>
</div>
<!--AJAX Message OBJECT-->
<style>
#response{
   display:none;
}
#display{
      display:none;

}
</style>
<div id="response">
<h4 id="msg" style="text-align:center"></h4>
</div>
<div id="process">
<div class="spinner-border text-secondary" role="status">
  <span class="sr-only">Loading...</span>
</div>
</div>
<input type="hidden" id="token" vlaue="{{deal.token}}">
<script>
       var tokenz="{{deal.token}}"

$(document).ready(function(){
   

    $('#approve').click(function(){
      console.log(tokenz)
      $('#process').modal();
        $.ajax({
            type: "POST",
            url: "{%url 'Backend:dealstatus'%}",
            data: { payload: "approve", token: tokenz },
             dataType: "json",
            success:function(resp){
                $('#response').text(resp.msg)
                location.reload()
            }
            
          })
          
        $('#request').on($.modal.AJAX_SEND, function(event, modal) {
        $('#process').modal();
          });

          $('#process').on($.modal.AJAX_SUCCESS, function(event, modal) {
            $('#response').modal();
              });
    });
});

//decline
$(document).ready(function(){
    $('#decline').click(function(){

        $.ajax({
            method: "POST",
            url: "{%url 'Backend:dealstatus'%}",
            data: { payload: "decline", token: tokenz },
            success:function(resp){
                $('#msg').text(resp.msg)
                location.reload()

            }
          })
          
        $('#request').on($.modal.AJAX_SEND, function(event, modal) {
        $('#process').modal();
          });

          $('#process').on($.modal.AJAX_SUCCESS, function(event, modal) {
            $('#response').modal();
              });
    })
});
//delete
$(document).ready(function(){
    $('#delete').click(function(){

        $.ajax({
            method: "POST",
            url: "{%url 'Backend:dealstatus'%}",
            data: { payload: "approve", token: tokenz },
            success:function(resp){
                $('#msg').text(resp.msg)
                
            }
          })
          
        $('#request').on($.modal.AJAX_SEND, function(event, modal) {
        $('#process').modal();
          });

          $('#process').on($.modal.AJAX_SUCCESS, function(event, modal) {
            $('#response').modal();
              });
    })
})
//suspend 
$(document).ready(function(){
    $('#suspend').click(function(){

        $.ajax({
            method: "POST",
            url: "{%url 'Backend:dealstatus'%}",
            data: { payload: "suspend", token: tokenz },
            success:function(resp){
                $('#msg').text(resp.msg)
                location.reload()

            }
          })
          
        $('#process').on($.modal.AJAX_SEND, function(event, modal) {
        $('#response').modal();
          });

          $('#process').on($.modal.AJAX_SUCCESS, function(event, modal) {
            $('#response').modal();
              });
    })
})
</script>
{% endblock%}

Backend/templates/backend/manage-user.html
{% extends 'base.html'%}

{% block content%}
<div class="container-fluid">
<table id="example" class="display nowrap">
    <thead>
        <tr>
            <th width="200">First Name</th>
        <th width="200">Last Name</th>

            <th tabulator-align="center">Email</th>
        <th tabulator-align="center">Account_Status</th>

            <th>User_level</th>
                 <th width="200">Last_login</th>
            <th width="200">Registration Date</th>


        </tr>
    </thead>
    <tbody>
    {% for u in user %}
        <tr>
       
            <td scope="row"><a href="{%url 'Backend:user-detail' u.pk %}">{{u.first_name}}</a></td>
                        <td scope="row">{{u.last_name}}</td>
                <td scope="row">{{u.email}}</td>
                 {% if u.is_active == False%}
        <td scope="row" style="color:red;">suspended</td> 
        {% else %}
                <td scope="row" style="color:green;">active</td> 
                {% endif %}
                {% if u.is_staff == False%}
        <td scope="row">Subscriber</td> 
        {% else %}
                <td scope="row">Staff</td> 
                {% endif %}

<td>{{u.last_login}}</td>
<td>{{u.date_joined}}</td>
</tr>
        {%endfor%}
    </tbody>
</table>

 </div>
<script>
$(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );

</script>
 <script type="text/javascript" src=" https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src ="https://code.jquery.com/jquery-3.3.1.js"></script>


<script type="text/javascript" src  = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.flash.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.html5.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/js/buttons.print.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.0/css/buttons.dataTables.min.css"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>



 
{% endblock %}