Backend/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name='Backend'
urlpatterns = [
    path('web-manager/',views.index,name="web-master"),
    path('manage-user/', views.manage_user,name="user-manager"),
    path('user-detail/<int:pk>', views.user_detail,name="details"),
    path('deal_request/<str:token>',views.save_deal,name="save-deal"),
        path('my_request/',views.save_deals,name="my-request"),
path('user_admin/',views.user_manage,name='user-admin'),
     path('deal_detail/<int:pk>',views.deal_details,name="deal-detail"),
    path('dealstatus/',views.deal_status,name="dealstatus"),
 path('request_record/',views.deal_record,name="request-record"),
  path('request_moderation/<str:code>',views.deal_moderation,name="deal_moderation"),
    path('request_moderation/',views.approve_request,name="reqstatus"),
        path('user_record/',views.users_record,name="user-record"),
            path('user_detail<int:pk>/',views.user_detail,name="user-detail"),
                path('settings/',views.settings,name="settings"),



]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

View/urls.py
from . import views
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'View'
urlpatterns = [
    path('',views.homes,name='home2'),
    path('deal-index/',views.home,name='home'),
url(r'^index',views.home,name='index'),
path('login/',views.login2,name='login'),
path('logout/',views.log_uerout,name='logout'),
    path('welcome/<str:token>', views.verifyAccount),
    path('signup/',views.create_account,name='signup2'),
    path('login/',views.verification_login,name='login_uri'),
    url(r'^profile/',views.user_profile,name='myprofile'),
    path('save_deal',views.save_deal,name='create_deal'),
    path('clear_deal/<str:token>',views.deal_clearance,name='clear_deal'),
    path('clearance/',views.save_clearance,name="verify_deal"),
    path('listing/<int:pk>',views.deal_deail,name="deal-details"),
    url(r'^signup',views.sign_up,name='sign-up'),
    path('save_form/',views.registar,name='registar'),
        path('mydeals/',views.user_deals,name='mydeal'),
    url(r'^request-deal/',views.deal_process,name="request_deal"),
        url(r'^dashboard/',views.dashboard,name="dashboard"),
   
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

appl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('View.urls')),
    path('deals_manager/',include('Backend.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Backend/models.py
from django.db import models

# Create your models here.
class EmailToken(models.Model):
    token= models.CharField(max_length=50)
    uid = models.BigIntegerField()

Backend/views.py
from django.shortcuts import render,reverse,redirect,HttpResponse,get_object_or_404
from View.models import Deals,Profile,Mydeals,Request
from django.contrib.auth.models import User
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import JsonResponse
from django.contrib import auth
import random
from Backend.sms import SMS
from Backend.mymail import MAIL
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
# Create your views here.
def index(request):
    deal = Deals.objects.all()
    return render(request,'backend/index.html',{'deal':deal})
def manage_user(request):
    profile=Profile.objects.all()
    users = User.objects.all()
    return render(request,'backend/manage-user.html',{'users':users,'profile':profile})
#Manage Use Details
def user_detail(request,pk):
    user = get_object_or_404(User,pk=pk)
    profile = get_object_or_404(Profile,user_id=user.pk)
    return render(request,'backend/user-detail.html',{'user':user,'profile':profile})
#User administration
@csrf_exempt
@require_http_methods(['POST'])
def user_manage(request):
    payload= request.POST.get('payload',None)
    token= request.POST.get('token',None)
    user = get_object_or_404(User,pk=token)


    
    if payload == "staff":
        content_type = ContentType.objects.get_for_model(Profile)
        permission = Permission.objects.get(codename='is_staff',content_type=content_type,)
        user.user_permissions.add(permission)

        user.save()      

        data ={'msg':'Approved'}      
        return JsonResponse(data)
    elif payload == "suspend":
        user.is_active = False
        user.save()
        data={'msg':'suspended'}
        return JsonResponse(data)
    elif payload == "enable":
        user.is_active = True
        user.save()
        data={'msg':'enabled'}
        return JsonResponse(data)
    else:
        user.delete()
        data={'msg':'deleted'}
        return JsonResponse(data)
    return redirect('Backend:index')
#Deal Request
def save_deal(request,token):
    track_code =   random.randint(100,1000)
    deal = get_object_or_404(Deals,token=token)
    if request.user.is_authenticated:
        uid = request.session['userId']
        user = get_object_or_404(User,pk=uid)
        mydeal = Mydeals.objects.create(deal_code=track_code)
        mydeal.save()
        mydeal.title=deal.title
        mydeal.deal_id=deal
        mydeal.owner = user
        mydeal.save()
        return redirect('View:mydeal')
    else:
        request.session['deal']=token
        return redirect('View:sign-up')
    return HttpResponse('Error')

#Deal Validation
def deal_details(request,pk):
    deal =get_object_or_404(Deals,pk=pk)
    uid=deal.op_id
    profile = get_object_or_404(Profile,pk=uid)
    
    user = get_object_or_404(User,pk=profile.user_id)
    return render(request,'backend/manage-deal.html',{'deal':deal,'profile':profile,'user':user})
#Deal Status
@csrf_exempt
@require_http_methods(['POST'])
def deal_status(request):
    payload= request.POST.get('payload',None)
    token= request.POST.get('token',None)
    uid = request.session['userId']
    user = get_object_or_404(User,pk=uid)


    deal= get_object_or_404(Deals,token=token) 
    deal.moderator=user
    deal.save()
    if payload == "approve":
        deal.valid=True
        deal.is_valid=True

        deal.save()      
        userename=user.first_name
        email=user.email
        data ={'msg':'Approved'}
        deal.status =True
        deal.save()
             
        return JsonResponse(data)
    elif payload == "decline":
        deal.valid =False
        deal.save()
        data={'msg':'Declined'}
        deal.status = False
        deal.save()
         
        return JsonResponse(data)

    elif payload == "suspend":
        deal.status = False
        deal.save()
        data={'msg':'Suspended'}
         
        return JsonResponse(data)
    else:
        deal.delete()
        data ={'msg':'deleted'}
        return JsonResponse(data)
    return redirect('Backend:index')

@csrf_protect
@require_http_methods(['POST'])
def save_deals(request):
    title= request.POST.get('title',None)
    about = request.POST.get('about',None)
    uid = request.session['userId']
    user = get_object_or_404(User,pk=uid)
    req = Request.objects.create(title=title,text=about,op=user)
    req.save()
    return redirect('View:dashboard')

#DEAL REQUEST RECORD
def deal_record(request):
    mydeal= Mydeals.objects.all()
    return render(request,'backend/deal_record.html',{'mydeal':mydeal})
#DEAL REQUEST MODERATION
def deal_moderation(request,code):
    mydeal= get_object_or_404(Mydeals, deal_code=code)
    #Get the Deal object
    deal_id = mydeal.deal_id_id
    deal = get_object_or_404(Deals,pk=deal_id)
    # Deal owner object
    deal_owner = deal.op_id
    profile_owner = get_object_or_404(Profile,pk=deal_owner)
    owner = get_object_or_404(User,pk=profile_owner.user_id)
    #Deal Request owner objeck
    request_user =get_object_or_404(User,pk=mydeal.owner_id)
    #Request Owner Profile
    profile_request =get_object_or_404(Profile,user_id=request_user.id)
    return render(request,'backend/request-details.html',{'mydeal':mydeal,'deal':deal,'owner':owner,'profile':profile_request,
                                                        'req':request_user,'profile_owner':profile_owner})
@csrf_exempt
@require_http_methods(['POST'])
def approve_request(request):
    payload= request.POST.get('payload',None)
    token= request.POST.get('token',None)


    deal= get_object_or_404(Mydeals,deal_code=token) 
    deal.save()
    if payload == "approve":
        deal.is_fufilled=True
        deal.save()
        deal.save()  
        deal.status='successful'    
        data ={'msg':'Approved'}
        deal.save()    
          
        return JsonResponse(data)
    elif payload == "decline":
        deal.is_fufilled =False
        deal.save()
        deal.status='declined'
        deal.save()
        data={'msg':'Declined'}
        deal.save()
         
        return JsonResponse(data)
    return redirect('Backend:request-record')

def users_record(request):
    users= User.objects.all()
    return render(request,'backend/manage-user.html',{'user':users})

#Settings
def settings(request):
    return render(request,'backend/settings.html')

Backend/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<!------ Include the above in your HEAD tag ---------->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="sumit kumar">
  

 <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
			  crossorigin="anonymous"></script>
  <title>Deals Connect Ng</title>
 
<!-- jQuery Modal -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
      

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="{% static 'css/panel.css'%}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/deal.css'%}" rel="stylesheet" type="text/css">
     <script src="{% static 'js/tabular/modules/accessor.js'%}"></script>
     <script src="{% static 'js/deal.js'%}"></script>

  <!--TABLE SCRIPT-->
          <script src="{% static 'js/tabular/modules/calculation_colums.js'%}"></script>
            <script src="{% static 'js/tabular/modules/download.js'%}"></script>
                        <script src="{% static 'css/tabular/modules/filter.js'%}"></script>
                              <script src="{% static 'css/tabular/modules/format.js'%}"></script>
        <script src="{% static 'js/tabular/modules/html_table_export.js'%}"></script>
                <script src="{% static 'js/tabular/modules/print.js'%}"></script>
                                <script src="{% static 'js/tabular/modules/select_row copy.js'%}"></script>
                        <script src="{% static 'js/tabular/modules/select_row.js'%}"></script>
                                                <script src="{% static 'js/tabular/modules/sort.js'%}"></script>

   <script src="{% static 'js/tabular/jquery_wrapper.js'%}"></script>
      <script src="{% static 'js/tabular/tabulator_core.js'%}"></script>
         <script src="{% static 'js/tabular/tabulator.js'%}"></script>
             <link  href="{% static 'css/tableexport.css' %}" rel="stylesheet" media="screen"  type="text/css">

         <script type="text/javascript" src="http://oss.sheetjs.com/js-xlsx/xlsx.full.min.js"></script>
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.0.5/jspdf.plugin.autotable.js"></script>
   <!--END SCRIPT-->

 <script src="https://use.fontawesome.com/07b0ce5d10.js"></script>
 
 </head>

<body>
  <!--=============================
                                             NAVIGATION
                                   =============================-->
  <!--top nav start=======-->
  <nav class="navbar navbar-inverse top-bar navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button> <span class="menu-icon" id="menu-icon"><i class="fa fa-times" aria-hidden="true" id="chang-menu-icon"></i></span>
        <a class="navbar-brand" href="#"><img src="https://lh3.googleusercontent.com/-N4NB2F966TU/WM7V1KYusRI/AAAAAAAADtA/fPvGVNzOkCo7ZMqLI6pPITE9ZF7NONmawCJoC/w185-h40-p-rw/logo.png" width="90%"> </a>
      </div>
      <div class="collapse navbar-collapse navbar-right" id="myNavbar">
        <form class="navbar-form navbar-left">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i> </button>
            </div>
          </div>
        </form>
        <ul class="nav navbar-nav">
          <li class=""><a href="#"><i class="fa fa-refresh"></i> Start Tour</a> </li>
          <li class=""><a href="#"><i class="fa fa-volume-up"></i></a> </li>
          <li class=""><a href="#"><i class="fa fa-envelope"></i> <span class="badge">5</span></a> </li>
          <li class=""><a href="#"><i class="fa fa-bell"></i> <span class="badge">9</span></a> </li>
          <li class="">
            <a href="#" class="user-profile"> <span class=""><img class="img-responsive" src="https://lh3.googleusercontent.com/-HxSAl6WJSI0/WM-dbkQ1ONI/AAAAAAAADuY/RsjaXC3tg4oBozCUYyLr12ZjZ1_Cl91mACJoC/w424-h319-p-rw/sumit.png"></span> </a>
          </li>
          <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sumit          
           <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <a href="#"><i class="fa fa-user"></i> Profile</a> </li>
              <li> <a href="#"><i class="fa fa-cog"></i> Setting</a> </li>
              <li> <a href="#"><i class="fa fa-power-off"></i> Logout</a> </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!--    top nav end===========-->
  <div class="wrapper" id="wrapper">
    <div class="left-container" id="left-container">
      <!-- begin SIDE NAV USER PANEL -->
      <div class="left-sidebar" id="show-nav">
        <ul id="side" class="side-nav">
          <li class="panel">
            <a id="panel1" href="javascript:;" data-toggle="collapse" data-target="#Dashboard"> <i class="fa fa-dashboard"></i> Dashboard
              <i class="fa fa-chevron-left pull-right" id="arow1"></i> </a>
           <!-- <ul class="collapse nav" id="Dashboard">
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
          <li class="panel">
            <a id="panel2" href="{% url 'Backend:web-master'%}" data-toggle="collapse" data-target="#charts"> <i class="fa fa-bar-chart-o"></i> New Deals
              <i class="fa fa-chevron-left pull-right" id="arow2"></i> </a>
            <!--<ul class="collapse nav" id="charts">
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
          <li class="panel">
            <a id="panel4" href="{% url 'Backend:request-record'%}" data-toggle="collapse" data-target="#clipboard"> <i class="fa fa-clipboard"></i> Deal Request
              <i class="fa fa fa-chevron-left pull-right" id="arow4"></i> </a>
           <!-- <ul class="collapse nav" id="clipboard">
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
          <li class="panel">
            <a id="panel5" href="{% url 'Backend:user-record' %}" data-toggle="collapse" data-target="#edit"> <i class="fa fa-edit"></i>
            User Administration
              <i class="fa fa fa-chevron-left pull-right" id="arow5"></i>
            </a>
           <!-- <ul class="collapse nav" id="edit">
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
          <li class="panel">
            <a id="panel6" href="javascript:;" data-toggle="collapse" data-target="#inbox"> <i class="fa fa-inbox"></i> Message
              <span class="label label-primary">new msz</span> <i class="fa fa fa-chevron-left pull-right" id="arow6"></i> </a>
           <!-- <ul class="collapse nav" id="inbox">
             <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
          <li class="panel">
            <a id="panel7" href="{% url 'Backend:settings'%}" data-toggle="collapse" data-target="#cogs"> <i class="fa fa-cogs"></i> Settings
              <span class="label label-warning">Warning</span> <i class="fa fa fa-chevron-left pull-right" id="arow7"></i> </a>
          <!--  <ul class="collapse nav" id="cogs">
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
          <li class="panel">
            <a id="panel8" href="javascript:;" data-toggle="collapse" data-target="#paper"> <i class="fa fa-paper-plane"></i> User Reviews
              <i class="fa fa fa-chevron-left pull-right" id="arow8"></i> </a>
            <!--<ul class="collapse nav" id="paper">
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Flot Charts</a> </li>
              <li> <a href="#"><i class="fa fa-angle-double-right"></i> Morris.js</a> </li>
            </ul>-->
          </li>
         
          <li class="panel">
            <a id="panel11" href="/logout" data-toggle="collapse" data-target="#pie-Chart">
              <i class="fa fa-lock"></i>logout
              <span class="label label-success">Supper</span> <i class="fa fa fa-chevron-left pull-right" id="arow11"></i> </a>
          
          </li>
        </ul>
      </div>
      <!-- END SIDE NAV USER PANEL -->
    </div>
    <div class="right-container" id="right-container">
     {%block content%}
  {% endblock%}   
  </div>
  
  <script src="js/jquery-3.1.1.js"></script>
  <script src="js/bootstrap.js"></script>
   
  <script type="text/javascript">
    $(document).ready(function() {
      $("#panel1").click(function() {
        $("#arow1").toggleClass("fa-chevron-left");
        $("#arow1").toggleClass("fa-chevron-down");
      });
        
      $("#panel2").click(function() {
        $("#arow2").toggleClass("fa-chevron-left");
        $("#arow2").toggleClass("fa-chevron-down");
      });
        
      $("#panel3").click(function() {
        $("#arow3").toggleClass("fa-chevron-left");
        $("#arow3").toggleClass("fa-chevron-down");
      });
        
      $("#panel4").click(function() {
        $("#arow4").toggleClass("fa-chevron-left");
          $("#arow4").toggleClass("fa-chevron-down");
      });
        
      $("#panel5").click(function() {
        $("#arow5").toggleClass("fa-chevron-left");
        $("#arow5").toggleClass("fa-chevron-down");
      });
        
      $("#panel6").click(function() {
        $("#arow6").toggleClass("fa-chevron-left");
        $("#arow6").toggleClass("fa-chevron-down");
      });
        
      $("#panel7").click(function() {
        $("#arow7").toggleClass("fa-chevron-left");
        $("#arow7").toggleClass("fa-chevron-down");
      });
        
      $("#panel8").click(function() {
        $("#arow8").toggleClass("fa-chevron-left");
        $("#arow8").toggleClass("fa-chevron-down");
      });
        
      $("#panel9").click(function() {
        $("#arow9").toggleClass("fa-chevron-left");
        $("#arow9").toggleClass("fa-chevron-down");
      });
        
      $("#panel10").click(function() {
        $("#arow10").toggleClass("fa-chevron-left");
        $("#arow10").toggleClass("fa-chevron-down");
      });
        
      $("#panel11").click(function() {
        $("#arow11").toggleClass("fa-chevron-left");
        $("#arow11").toggleClass("fa-chevron-down");
      });
        
      $("#menu-icon").click(function() {
        $("#chang-menu-icon").toggleClass("fa-bars");
        $("#chang-menu-icon").toggleClass("fa-times");
        $("#show-nav").toggleClass("hide-sidebar");
        $("#show-nav").toggleClass("left-sidebar");
          
        $("#left-container").toggleClass("less-width");
        $("#right-container").toggleClass("full-width");
      });
        
     
        
    });
  </script>
    
    
    
    
    
    
    
    
    
    
    
    
    
</body>

</html>